plugins {
    id 'java'
    id 'application'
    id 'jacoco'
}

    group 'com.github.jyhsu2000'
    version '1.0-SNAPSHOT'

    application {
    mainClassName 'com.github.jyhsu2000.Main'
}

    repositories {
    mavenCentral()
}

    dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.8.1'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.8.1'
}

    test {
    useJUnitPlatform()
    finalizedBy jacocoTestReport
}

    jacocoTestReport {
    dependsOn test
    reports {
    xml.enabled = true
    }
}
